### PR TITLE
Tests!

### PR DESCRIPTION
**Pull request by AntoineDao**
This PR contains a first batch of tests for Operators and Recipes. It also demonstrates a couple of these resources in a pre-determined "folder format".

PS: A lot of files have changed because I deleted pretty much all of the old tests... :disappointed:

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Is this expected that the PR doesn't trigger the tests on Travis?

**Comment by AntoineDao** [comment]
Nope. It should have kicked off a travis job...

**Comment by AntoineDao** [comment]
Correction, the tests have run (and PASSED!) but Github wasn't notified: https://travis-ci.org/github/ladybug-tools/queenbee

**Comment by mostaphaRoudsari** [comment]
Oh great! Let's merge this in then.

**Comment by AntoineDao** [comment]
Finishing up some more tests this afternoon. I'll push and merge after that 😄

**Comment by AntoineDao** [comment]
Tomorrow we document!! 📑

**Comment by AntoineDao** [comment]
Look at that nice little Travis badge!

**Pull request merged**
