### PR TITLE
fix(reference): set type to parameter/artifact Reference

### PR DESCRIPTION
**Pull request by MingboPeng**

### CODE REVIEW

**Comment by MingboPeng** [comment]
Addressing https://github.com/ladybug-tools/queenbee/issues/143

**Review by AntoineDao — CHANGES_REQUESTED** [review]
We can switch to using `constr` to avoid having an `Enum` value for types if it makes it easier for dotnet 😄

I would rather not change the string value for the types though as this introduces breaking changes to the schema. 

That being said, could you explain why you think we need the `type` name to match the class name? Is this the way you have designed the honeybee schema? Was it for dotnet SDK purposes or was there another reason behind this?

**Comment by MingboPeng** [comment]
Thanks @AntoineDao, I try to explain it here https://github.com/ladybug-tools/queenbee/issues/143#issuecomment-696747587.

**Comment by mostaphaRoudsari** [comment]
This will be a breaking change and we will address it with the other breaking changes to Queenbee!

**Comment by mostaphaRoudsari** [comment]
I'm closing this PR in favor of #152 which will address this issue.

**Pull request closed without merging**
